name: Pull Request

on:
  pull_request:
   types:
    - opened
    - synchronize
    - reopened

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pre-commit
      run: |
        pip install pre-commit==3.3.3

    - name: Run pre-commit hooks
      run: pre-commit run --all-files
