name: Release

on:
  push:
    branches:
    - master

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION:                "3.12.2"
      GATOR_VERSION:               "3.12.0"
      DATREE_VERSION:              "1.9.19"
      YQ_VERSION:                  "4.34.2"
      K8S_SCHEMA_VERSION:          "1.28.5"
      K8S_SCHEMA_REPO_COMMIT_SHA:  "53453a08d42fcc76ab2f8658f11d20aa07197ba8" # https://github.com/yannh/kubernetes-json-schema
      CRDS_SCHEMA_REPO_COMMIT_SHA: "89a756e59d7c9524ff07a7408a1d6b8dae5ccce5" # https://github.com/datreeio/CRDs-catalog/tree/main
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          paritytech/kube-manifests-validation
        tags: |
          type=raw,value=k8s-${{ env.K8S_SCHEMA_VERSION }}-gator-${{ env.GATOR_VERSION }}-datree-${{ env.DATREE_VERSION }}-{{sha}},priority=1002
          type=raw,value={{branch}}-{{sha}},priority=1001
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          HELM_VERSION=${{ env.HELM_VERSION }}
          GATOR_VERSION=${{ env.GATOR_VERSION }}
          DATREE_VERSION=${{ env.DATREE_VERSION }}
          YQ_VERSION=${{ env.YQ_VERSION }}
          K8S_SCHEMA_VERSION=${{ env.K8S_SCHEMA_VERSION }}
          K8S_SCHEMA_REPO_COMMIT_SHA=${{ env.K8S_SCHEMA_REPO_COMMIT_SHA }}
          CRDS_SCHEMA_REPO_COMMIT_SHA=${{ env.CRDS_SCHEMA_REPO_COMMIT_SHA }}
          VCS_REF=${{ github.ref }}
          BUILD_DATE=${{ github.event.release.published_at }}

